// Install the VSCode extension REST Client (humao.rest-client) 
// To execute this request on VSCode (it is like Postman inside vs code)


# List the projects
GET http://127.0.0.1:3333/projects?title=react&owner=ricardo

###
# create a project
POST http://127.0.0.1:3333/projects
Content-Type: application/json

{
  "title": "Aplicativo React Native",
  "owner": "Ricardo Ferreira"
}

###
# edit a project
PUT http://127.0.0.1:3333/projects/2

###
# delete a project
DELETE http://127.0.0.1:3333/projects/1